const FIREBASE_KEY="AIzaSyAXGIS3BQKSzNfxOqhHPLKo0XAtIzmXKfU"
const FIREBASE_DOMAIN="online-photo-album-project.firebaseapp.com"
const FIREBASE_PROJECT_ID="online-photo-album-project"
const FIREBASE_STORAGE_BUCKET="online-photo-album-project.appspot.com"
const FIREBASE_MESSAGE_SENDER_ID="329673590806"
const FIREBASE_APP_ID="1:329673590806:web:b0f7ef75b8f5eba627cd37"

export {FIREBASE_APP_ID, FIREBASE_DOMAIN, FIREBASE_KEY, FIREBASE_PROJECT_ID, FIREBASE_MESSAGE_SENDER_ID, FIREBASE_STORAGE_BUCKET}